<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2021/12/01 10:56:39

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=orangehrm_mysql;charset=utf8mb4',
  'username' => 'dmwangi',
  'password' => 'a>}6TG7nbqKcY68W',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
